#include "ui/Localization.h"

#include <map>
#include <set>
#include <string>

namespace hexmap {
namespace i18n {
namespace {

Language g_lang = Language::Vietnamese;

/// Khoá thiếu bản dịch, gom lại để hiện số lượng trong Settings.
std::set<std::string>& missingKeys() {
    static std::set<std::string> s;
    return s;
}

using Table = std::map<std::string, const char*>;

// ── Tiếng Việt ────────────────────────────────────────────────────────
const Table& tableVI() {
    static const Table t = {
        // Menu
        {"tree.title",              "SCREEN SETUP"},
        {"tree.toggle",             "Ẩn / hiện cây Screen Setup"},
        {"tree.mask",               "Mặt nạ"},
        {"tree.vis.tip",            "Bật / tắt hiển thị"},
        {"tool.select",             "Công cụ chọn"},
        {"tool.addslice",           "Thêm Slice"},
        {"tool.addmask",            "Thêm Mặt nạ"},
        {"tool.snap.tip",           "Hút điểm về đường gióng: mép và đường giữa máy chiếu, điểm của slice khác. Giữ ALT trong lúc kéo để tạm tắt."},
        {"tool.testcard",           "Ảnh căn"},
        {"tool.apply",              "Áp dụng"},
        {"tool.apply.tip",          "Đưa hình ra máy chiếu (fullscreen). F11"},
        {"screen.settings",         "THIẾT LẬP SCREEN"},
        {"screen.name",             "TÊN SCREEN"},
        {"slice.name",              "TÊN SLICE"},
        {"screen.enabled",          "Bật screen này"},
        {"screen.routing",          "ĐƯA RA THIẾT BỊ"},
        {"screen.resolution",       "Độ phân giải ảo:"},
        {"screen.slices",           "SLICE TRONG SCREEN NÀY"},
        {"mask.settings",           "THIẾT LẬP MẶT NẠ"},
        {"mask.created",            "Đã tạo mặt nạ - kéo nút để căn theo mép vật thể"},
        {"mask.exists",             "Slice này đã có mặt nạ rồi"},
        {"mask.noslice",            "Chọn một slice trước đã"},
        {"nav.composition",         "COMPOSITION"},
        {"nav.mapping",             "ADVANCED MAPPING"},
        {"nav.sensor",              "SENSOR I/O"},
        {"nav.settings",            "..."},
        {"nav.nooutput",            "CHƯA CÓ OUTPUT"},
        {"topbar.showmode",         "Chế Độ Diễn"},
        {"topbar.showmode.tip",     "Ẩn/hiện tay cầm chỉnh sửa (Space)"},
        {"topbar.testgrid",         "Lưới Test"},
        {"topbar.testgrid.tip",     "Bật lưới căn chỉnh trên máy chiếu (G)"},
        {"topbar.autocalib",        "Tự Hiệu Chỉnh"},
        {"topbar.autocalib.tip",    "Tự hiệu chỉnh cảm biến giả lập (A)"},
        {"topbar.fullscreen.tip",   "Toàn màn hình cửa sổ chiếu (F11)"},
        {"topbar.save.tip",         "Lưu dự án (.hexmap)"},
        {"topbar.load.tip",         "Mở dự án (.hexmap)"},
        {"topbar.lang.tip",         "Đổi ngôn ngữ (VI / EN)"},
        {"topbar.latency",          "ĐỘ TRỄ:"},
        {"browser.title",           "THƯ VIỆN"},
        {"browser.rescan",          "Quét lại thư mục bin/data/media"},
        {"browser.media",           "MEDIA"},
        {"browser.empty",           "Chưa có file nào trong bin/data/media"},
        {"browser.generator.tip",   "Nguồn hình sinh bằng shader — không cần file, chạy được ngay. Chọn một ô clip trước rồi bấm vào đây."},
        {"browser.noTarget",        "Chọn một ô clip trước đã"},
        {"browser.target",          "Đích: Layer %d · Cột %d"},
        {"browser.browse",          "Chọn file khác..."},
        {"browser.hapOk",           "Nhiều khả năng là HAP - tốt"},
        {"browser.hapWarn",         "Có thể KHÔNG phải HAP - dễ tụt fps"},
        {"mon.preview",             "XEM TRƯỚC"},
        {"mon.active",              "ĐANG CHIẾU"},
        {"inspector.title",         "THUỘC TÍNH"},
        {"inspector.tab.clip",      "CLIP"},
        {"inspector.tab.layer",     "LAYER %d"},
        {"layer.blend.label",       "BLEND"},
        {"layer.opacity.short",     "L%d ĐM"},
        {"layer.transition.label",  "CHUYỂN"},
        {"layer.props.title",       "LAYER %d"},
        {"layer.props.solo",        "Solo"},
        {"layer.props.bypass",      "Bypass"},
        {"mon.live",                "TRỰC TIẾP"},
        {"comp.cellhint",           "Bấm để phát  ·  bấm phải để xem thêm"},
        {"clip.ctx.choose",         "Chọn file từ folder..."},
        {"clip.ctx.duplicate",      "Nhân bản"},
        {"clip.ctx.copy",           "Sao chép"},
        {"clip.ctx.paste",          "Dán"},
        {"clip.ctx.rename",         "Đổi tên"},
        {"clip.ctx.info",           "Thông tin"},
        {"clip.ctx.delete",         "Xoá"},
        {"dialog.ok",               "Đồng ý"},
        {"dialog.cancel",           "Huỷ"},
        {"clip.preview.tip",        "Xem trước clip này"},
        {"map.mode.input",          "VÙNG LẤY"},
        {"map.mode.output",         "ĐƯỜNG RA"},
        {"map.breadcrumb.input",    "Nguồn nội dung: %dx%d"},
        {"map.breadcrumb.output",   "%s (%s · %dx%d)"},
        {"map.breadcrumb.noassign", "Chưa gán màn hình"},
        {"map.mode.input.note",     "Kéo vùng lấy trên canvas - phần nào của hình được chiếu"},
        {"map.mode.output.note",    "Kéo góc trên khung máy chiếu - hình nằm ở đâu trên vật thể"},
        {"map.input.hint",          "Kéo giữa để di chuyển  |  kéo góc để đổi kích thước"},
        {"map.sidebar",             "Ẩn / hiện bảng thuộc tính"},
        {"slice.settings",          "THIẾT LẬP SLICE"},
        {"sen.devices",             "THIẾT BỊ"},
        {"perf.title",              "HIỆU NĂNG"},
        {"cal.section",             "CALIBRATION & VÙNG CẢM ỨNG"},
        {"menu.project",            "Dự án"},
        {"menu.project.new",        "Tạo mới"},
        {"menu.project.open",       "Mở..."},
        {"menu.project.save",       "Lưu"},
        {"menu.output",             "Output"},
        {"menu.output.mapping",     "Mapping (chỉnh trong app)..."},
        {"menu.output.advanced",    "Advanced Output (thông số)..."},
        {"menu.output.sendto",      "Đưa output ra màn hình:"},
        {"menu.output.windowed",    "Về chế độ cửa sổ (để kéo)"},
        {"menu.output.fullscreen",  "Fullscreen / thoát"},
        {"menu.output.nodisplay",   "Không đọc được danh sách màn hình"},
        {"menu.output.primary",     "  (chính)"},
        {"menu.sensor",             "Sensor"},
        {"menu.sensor.panel",       "Sensor & Calibration..."},
        {"menu.sensor.mock",        "Chạy Mock (giả lập)"},
        {"menu.sensor.osc",         "Chạy OSC (cổng 9000)"},
        {"menu.sensor.stop",        "Dừng sensor"},
        {"menu.sensor.autocal",     "Auto-calibrate (Mock)"},
        {"menu.sensor.crosshair",   "Hiện dấu thập calibration"},
        {"menu.view",               "Xem"},
        {"menu.settings",           "Cài đặt"},
        {"menu.settings.open",      "Cài đặt..."},
        {"status.sensor.on",        "SENSOR: đang chạy"},
        {"status.sensor.off",       "SENSOR: tắt"},

        // Cửa sổ
        {"win.composition",         "Composition"},
        {"win.mapping",             "Mapping"},
        {"win.advanced",            "Advanced Output"},
        {"win.preview",             "Xem trước"},
        {"win.sensor",              "Sensor & Calibration"},
        {"win.perf",                "Hiệu năng"},
        {"win.clip",                "Clip"},
        {"win.settings",            "Cài đặt"},

        // Settings
        {"set.language",            "Ngôn ngữ"},
        {"set.language.note",       "Đổi ngôn ngữ có hiệu lực ngay."},
        {"set.output",              "Output"},
        {"set.output.default",      "Màn hình mặc định"},
        {"set.output.none",         "Không tự đưa"},
        {"set.vsync",               "Đồng bộ dọc (vsync)"},
        {"set.media",               "Media"},
        {"set.media.budget",        "Số media giữ trong cache"},
        {"set.media.budget.note",   "Cao: đổi clip mượt. Thấp: đỡ VRAM."},
        {"set.media.warnhap",       "Cảnh báo khi file không phải HAP"},
        {"set.diag",                "Chẩn đoán"},
        {"set.perflog",             "Ghi log hiệu năng"},
        {"set.perflog.interval",    "Chu kỳ ghi (giây)"},
        {"set.perflog.note",        "Ghi vào bin/data/perf.log — dùng khi cần tìm nguyên nhân giật."},
        {"set.startup",             "Khởi động"},
        {"set.autoplay",            "Tự phát clip đầu tiên"},
        {"set.save",                "Lưu cài đặt"},
        {"set.reset",               "Về mặc định"},
        {"set.saved",               "Đã lưu cài đặt"},
        {"set.missing",             "Khoá thiếu bản dịch"},

        // Composition
        {"comp.deck",               "Deck:"},
        {"comp.clearall",           "Dừng hết"},
        {"comp.hint",               "Bấm ô clip = phát  |  Bấm số cột = phát cả cột  |  Ctrl+bấm ô = chọn file"},
        {"layer.opacity",           "ĐỘ MỜ"},
        {"comp.master",             "Master"},
        {"comp.empty",              "Lưới rỗng"},
        {"comp.triggercol",         "Phát cả cột %d"},
        {"layer.solo.tip",          "Solo - ẩn mọi layer khác"},
        {"layer.bypass.tip",        "Bypass - tắt layer"},
        {"layer.clear.tip",         "Dừng layer"},
        {"layer.transition.tip",    "A10 - thời lượng chuyển clip (crossfade). 0 = cắt thẳng."},

        // Mapping
        {"map.showcontent",         "Hiện nội dung"},
        {"map.hint",                "Kéo điểm để căn chỉnh  |  bấm vào slice để chọn"},
        {"map.selecthint",          "Bấm vào một slice để chọn"},
        {"map.outside",             "%d điểm nằm NGOÀI khung máy chiếu"},
        {"map.noscreen",            "Chưa có screen nào"},

        // Advanced output
        {"adv.overlay",             "Hiện overlay chỉnh sửa"},
        {"adv.grid",                "Lưới test"},
        {"adv.addscreen",           "Thêm màn chiếu"},
        {"adv.addslice",            "+ Thêm slice"},
        {"adv.slicelist",           "Slice (trên cùng ở cuối danh sách):"},
        {"adv.selected",            "Slice đang chọn: %s"},
        {"adv.noslice",             "Chọn một slice để chỉnh chi tiết"},
        {"adv.inputorigin",         "VÙNG LẤY - GỐC"},
        {"adv.inputsize",           "VÙNG LẤY - KÍCH THƯỚC"},
        {"adv.source",              "LẤY NỘI DUNG TỪ"},
        {"adv.source.tip",          "Composition: hình đã trộn xong của mọi layer — dùng khi nhiều máy chiếu ghép thành MỘT bề mặt.  |  Layer: chỉ một layer, chưa trộn — dùng khi các bề mặt chạy nội dung ĐỘC LẬP nhau."},
        {"adv.src.comp",            "Composition (đã trộn)"},
        {"adv.src.layer",           "Một Layer riêng"},
        {"adv.src.which",           "LAYER SỐ"},
        {"adv.src.missing",         "Layer này không còn tồn tại — slice đang tạm lấy Composition. Chọn lại layer khác."},
        {"adv.warptype",            "LOẠI WARP"},
        {"adv.warptype.tip",        "Corner pin: mặt PHẲNG, 4 góc.  |  Mesh: lưới N×M, mỗi ô phẳng.  |  Bezier: mặt CONG trơn 16 điểm — dùng cho cột tròn, vòm, tượng. Đổi loại vẫn giữ nguyên bốn góc đã căn."},
        {"adv.reset",               "Đặt lại"},
        {"adv.delete",              "Xoá"},
        {"adv.corners",             "GÓC (NHẬP SỐ)"},
        {"adv.broken",              "  ! Warp suy biến - không dùng cho sensor được"},
        {"adv.color",               "Màu (F19)"},
        {"adv.softedge",            "Hoà viền (F20)"},
        {"adv.meshgrid",            "LƯỚI (CỘT X HÀNG)"},
        {"adv.overlay.tip",         "TẮT khi chạy show - khán giả không được thấy handle"},
        {"adv.solo",                "solo"},
        {"adv.color.note",          "Cần khi ghép nhiều máy chiếu: mỗi máy một sắc độ."},
        {"adv.color.brightness",    "ĐỘ SÁNG"},
        {"adv.color.contrast",      "TƯƠNG PHẢN"},
        {"adv.color.gamma",         "GAMMA"},
        {"adv.color.rgb",           "CÂN BẰNG RGB"},
        {"adv.color.opacity",       "Độ mờ slice"},
        {"adv.color.reset",         "Đặt lại màu"},
        {"adv.color.default",       "(mặc định)"},
        {"adv.color.edited",        "(đã chỉnh)"},
        {"adv.edge.note1",          "Ghép 2 máy chiếu: cho chồng nhau 10-20%%,"},
        {"adv.edge.note2",          "mỗi máy làm mờ dần về phía mép chồng."},
        {"adv.edge.left",           "TRÁI"},
        {"adv.edge.right",          "PHẢI"},
        {"adv.edge.top",            "TRÊN"},
        {"adv.edge.bottom",         "DƯỚI"},
        {"adv.edge.gamma",          "ĐỘ CONG"},
        {"adv.edge.gamma.tip",      "1.0 = tuyến tính. Máy chiếu thật thường cần 1.8-2.4 vì đáp ứng gamma của chúng phi tuyến."},
        {"adv.edge.mid",            "ĐIỂM GIỮA"},
        {"adv.edge.reset",          "Đặt lại viền"},
        {"adv.edge.off",            "(tắt)"},
        {"adv.edge.on",             "(đang bật)"},
        {"adv.corner.tl",           "TRÊN-TRÁI"},
        {"adv.corner.tr",           "TRÊN-PHẢI"},
        {"adv.corner.br",           "DƯỚI-PHẢI"},
        {"adv.corner.bl",           "DƯỚI-TRÁI"},
        {"adv.corner.rejected",     "Vị trí góc bị từ chối: tứ giác sẽ lõm hoặc tự cắt"},
        {"adv.mesh.hint",           "Kéo điểm lưới trong cửa sổ Mapping"},
        {"mask.title",              "Mặt nạ bezier (F12)"},
        {"mask.note",               "Cắt ánh sáng theo đúng bóng vật thể thật."},
        {"mask.enabled",            "Bật mặt nạ"},
        {"mask.edit",               "Chỉnh mặt nạ"},
        {"mask.edit.tip",           "Khi bật, kéo chuột trong cửa sổ Mapping tác động lên nút mặt nạ chứ không phải góc keystone."},
        {"mask.invert",             "Đảo (khoét lỗ)"},
        {"mask.feather",            "LÀM MỜ MÉP"},
        {"mask.feather.tip",        "Mép sắc phơi ra mọi sai số căn chỉnh với cạnh vật thể thật. Vài phần trăm là đủ giấu."},
        {"mask.shape.rect",         "Hình chữ nhật"},
        {"mask.shape.ellipse",      "Hình elip"},
        {"mask.clear",              "Xoá mặt nạ"},
        {"mask.nodes",              "%d nút"},
        {"mask.empty",              "Chưa có hình. Chọn một hình dựng sẵn để bắt đầu."},
        {"mask.tooFew",             "Cần ít nhất 3 nút thì mặt nạ mới có tác dụng."},
        {"mask.hint",               "Kéo nút để căn  |  bấm lên đường = thêm nút  |  chuột phải nút = xoá"},
        {"mask.hint.handle",        "Ctrl+kéo nút = uốn cong  |  Shift+bấm nút = duỗi thẳng"},
        {"mask.cannotRemove",       "Không xoá được: mặt nạ cần ít nhất 3 nút"},
        {"mask.full",               "Đã đạt số nút tối đa"},

        // Clip
        {"clip.nosel",              "Bấm icon mắt trên một ô clip để xem thuộc tính"},
        {"clip.empty",              "Ô này trống"},
        {"clip.name",               "Tên"},
        {"clip.transport",          "Transport"},
        {"clip.play",               "Phát"},
        {"clip.pause",              "Tạm dừng"},
        {"clip.stop",               "Dừng"},
        {"clip.playhead",           "Đầu phát"},
        {"clip.direction",          "Chiều"},
        {"clip.speed",              "Tốc độ"},
        {"clip.inout",              "Cắt đầu / cuối"},
        {"clip.endaction",          "Hết clip thì"},
        {"clip.trigger",            "Kiểu bấm"},
        {"clip.transform",          "Biến đổi"},
        {"clip.position",           "Vị trí"},
        {"clip.scale",              "Tỉ lệ"},
        {"clip.rotation",           "Xoay"},
        {"clip.fliph",              "Lật ngang"},
        {"clip.flipv",              "Lật dọc"},
        {"clip.resetxform",         "Đặt lại biến đổi"},
        {"clip.blending",           "Hoà trộn"},
        {"clip.opacity",            "Độ mờ"},
        {"clip.blend",              "BLEND"},
        {"clip.where",              "Layer %d  /  Cột %d"},
        {"clip.mediainfo",          "%.0f x %.0f  |  %.2f s"},
        {"clip.dir.fwd",            "Thuận"},
        {"clip.dir.rev",            "Ngược"},
        {"clip.dir.pp",             "Ping-pong"},
        {"clip.end.loop",           "Lặp"},
        {"clip.end.stop",           "Dừng"},
        {"clip.end.hold",           "Giữ khung cuối"},
        {"clip.end.next",           "Clip kế tiếp"},
        {"clip.end.rand",           "Ngẫu nhiên"},
        {"clip.trig.toggle",        "Toggle"},
        {"clip.trig.piano",         "Piano (giữ)"},

        // Sensor
        {"sen.source",              "NGUỒN"},
        {"sen.run",                 "Chạy"},
        {"sen.stop",                "Dừng"},
        {"sen.running",             "đang chạy"},
        {"sen.stopped",             "đang dừng"},
        {"sen.points",              "Điểm chạm: %d   (có ID bền vững: %d)"},
        {"sen.filter",              "Lọc nhiễu (phím F): %s"},
        {"cal.title",               "Calibration: %s"},
        {"cal.step",                "Bước %d/4: chạm vào dấu thập trên VẬT THỂ THẬT"},
        {"cal.target",              "Điểm mục tiêu: (%.2f, %.2f) của slice"},
        {"cal.crosshair",           "Hiện dấu thập trên máy chiếu (phím C)"},
        {"cal.auto",                "Auto-calibrate (Mock)"},
        {"cal.add",                 "Ghi điểm này"},
        {"cal.skip",                "Bỏ qua"},
        {"cal.solve",               "Giải"},
        {"cal.clear",               "Xoá hết"},
        {"cal.recorded",            "Đã ghi: %d điểm (%d đang bật)"},
        {"cal.error",               "Sai số: %.2f px (max %.2f) - %s"},
        {"cal.good",                "TỐT"},
        {"cal.bad",                 "NÊN CALIBRATE LẠI"},
        {"cal.notyet",              "Chưa calibrate"},
        {"cal.points",              "Các điểm đã ghi"},
        {"cal.none",                "Chưa có hồ sơ calibration"},
        {"sen.type.mock",           "Mock (giả lập)"},
        {"sen.type.osc",            "OSC / UDP"},
        {"sen.type.tuio",           "TUIO (cổng 3333)"},
        {"common.on.caps",          "BẬT"},
        {"common.off.caps",         "TẮT"},
        {"cal.auto.tip",            "Suy ra H_s từ phạm vi đã biết của MockSource. Để thử cả chuỗi mà không cần phần cứng."},
        {"cal.inlier",              "Inlier: %d / %d"},
        {"cal.pair",                "#%d  sensor(%.0f, %.0f) -> out(%.0f, %.0f)%s"},
        {"cal.outlier",             "   [RÁC]"},

        // Trigger zone
        {"zone.title",              "Vùng cảm ứng (G17)   -   đã kích hoạt: %d"},
        {"zone.last",               "Gần nhất: %s"},
        {"zone.add",                "+ Thêm vùng"},
        {"zone.none",               "Chưa có vùng nào. Chạm vào vật thể sẽ không làm gì."},
        {"zone.enabled",            "Bật"},
        {"zone.delete",             "Xoá vùng"},
        {"zone.position",           "Vị trí"},
        {"zone.size",               "Kích thước"},
        {"zone.action",             "Hành động"},
        {"zone.layer",              "Layer"},
        {"zone.column",             "Cột"},
        {"zone.cooldown",           "Chống dội"},
        {"zone.touching",           "   [ĐANG CHẠM]"},
        {"zone.add.tip",            "Vùng định nghĩa trong không gian CANVAS. Chỉnh lại keystone không làm lệch vùng."},
        {"zone.name",               "Tên"},
        {"zone.act.none",           "Không"},
        {"zone.act.clip",           "Phát clip"},
        {"zone.act.column",         "Phát cả cột"},
        {"zone.act.clearlayer",     "Dừng layer"},
        {"zone.act.clearall",       "Dừng hết"},
        {"zone.cooldown.tip",       "BẮT BUỘC với sensor thật. Một cú chạm sinh ra hàng chục sự kiện Down; không chặn dội thì clip bị trigger lại 30 lần/giây."},

        // Perf
        {"perf.frame",              "Frame: avg %.2f ms  p99 %.2f ms"},
        {"perf.latency",            "Độ trễ sensor:"},
        {"perf.latency.note",       "(chưa kể input lag của máy chiếu:"},
        {"perf.latency.note2",      " 16-80ms - bật Low Latency Mode)"},
        {"perf.nosensor",           "Sensor chưa chạy"},
        {"perf.dropped",            "Frame sensor bỏ qua: %llu"},
        {"perf.overflow",           "Ring overflow: 0"},
        {"perf.overflow.bad",       "! Ring overflow: %llu - MẤT sự kiện"},
        {"perf.malformed",          "Gói OSC hỏng: %llu"},
        {"perf.drawn",              "Layer vẽ: %d   Slice vẽ: %d"},
        {"perf.media",              "Media nạp: %d   Đã dọn: %d"},
        {"perf.vram",               "VRAM (ước tính): %s"},

        // Chung
        {"common.on",               "BẬT"},
        {"common.off",              "TẮT"},
        {"preview.nocontent",       "Chưa có nội dung"},
    };
    return t;
}

// ── English ───────────────────────────────────────────────────────────
const Table& tableEN() {
    static const Table t = {
        {"tree.title",              "SCREEN SETUP"},
        {"tree.toggle",             "Show / hide the Screen Setup tree"},
        {"tree.mask",               "Mask"},
        {"tree.vis.tip",            "Toggle visibility"},
        {"tool.select",             "Select tool"},
        {"tool.addslice",           "Add Slice"},
        {"tool.addmask",            "Add Mask"},
        {"tool.snap.tip",           "Snap to guides: projector edges and centre, control points of other slices. Hold ALT while dragging to bypass."},
        {"tool.testcard",           "Test Card"},
        {"tool.apply",              "Apply"},
        {"tool.apply.tip",          "Send the image to the projector (fullscreen). F11"},
        {"screen.settings",         "SCREEN SETTINGS"},
        {"screen.name",             "SCREEN NAME"},
        {"slice.name",              "SLICE NAME"},
        {"screen.enabled",          "Enable this screen"},
        {"screen.routing",          "DEVICE ROUTING"},
        {"screen.resolution",       "Virtual resolution:"},
        {"screen.slices",           "SLICES IN THIS SCREEN"},
        {"mask.settings",           "MASK SETTINGS"},
        {"mask.created",            "Mask created - drag nodes to trace the object edge"},
        {"mask.exists",             "This slice already has a mask"},
        {"mask.noslice",            "Select a slice first"},
        {"nav.composition",         "COMPOSITION"},
        {"nav.mapping",             "ADVANCED MAPPING"},
        {"nav.sensor",              "SENSOR I/O"},
        {"nav.settings",            "..."},
        {"nav.nooutput",            "NO OUTPUT"},
        {"topbar.showmode",         "Show Mode"},
        {"topbar.showmode.tip",     "Hide/show edit handles (Space)"},
        {"topbar.testgrid",         "Test Grid"},
        {"topbar.testgrid.tip",     "Toggle alignment grid on projector (G)"},
        {"topbar.autocalib",        "Auto Calib"},
        {"topbar.autocalib.tip",    "Auto-calibrate mock sensor (A)"},
        {"topbar.fullscreen.tip",   "Fullscreen projector window (F11)"},
        {"topbar.save.tip",         "Save project (.hexmap)"},
        {"topbar.load.tip",         "Open project (.hexmap)"},
        {"topbar.lang.tip",         "Switch language (VI / EN)"},
        {"topbar.latency",          "LATENCY:"},
        {"browser.title",           "LIBRARY"},
        {"browser.rescan",          "Rescan bin/data/media"},
        {"browser.media",           "MEDIA"},
        {"browser.empty",           "No files in bin/data/media"},
        {"browser.generator.tip",   "Shader-generated source — no file needed, runs immediately. Pick a clip cell first, then click here."},
        {"browser.noTarget",        "Select a clip cell first"},
        {"browser.target",          "Target: Layer %d - Column %d"},
        {"browser.browse",          "Browse for a file..."},
        {"browser.hapOk",           "Most likely HAP - good"},
        {"browser.hapWarn",         "May NOT be HAP - risks dropping frames"},
        {"mon.preview",             "PREVIEW"},
        {"mon.active",              "ACTIVE COMPOSITION"},
        {"inspector.title",         "PROPERTIES"},
        {"inspector.tab.clip",      "CLIP"},
        {"inspector.tab.layer",     "LAYER %d"},
        {"layer.blend.label",       "BLEND"},
        {"layer.opacity.short",     "L%d OP"},
        {"layer.transition.label",  "XFADE"},
        {"layer.props.title",       "LAYER %d"},
        {"layer.props.solo",        "Solo"},
        {"layer.props.bypass",      "Bypass"},
        {"mon.live",                "LIVE"},
        {"comp.cellhint",           "Click to play  ·  right-click for more"},
        {"clip.ctx.choose",         "Choose file from folder..."},
        {"clip.ctx.duplicate",      "Duplicate"},
        {"clip.ctx.copy",           "Copy"},
        {"clip.ctx.paste",          "Paste"},
        {"clip.ctx.rename",         "Rename"},
        {"clip.ctx.info",           "Info"},
        {"clip.ctx.delete",         "Delete"},
        {"dialog.ok",               "OK"},
        {"dialog.cancel",           "Cancel"},
        {"clip.preview.tip",        "Preview this clip"},
        {"map.mode.input",          "INPUT SELECTION"},
        {"map.mode.output",         "OUTPUT ROUTING"},
        {"map.breadcrumb.input",    "Source content: %dx%d"},
        {"map.breadcrumb.output",   "%s (%s · %dx%d)"},
        {"map.breadcrumb.noassign", "No display assigned"},
        {"map.mode.input.note",     "Drag the input rect on the canvas - which part of the image is projected"},
        {"map.mode.output.note",    "Drag corners on the projector frame - where the image sits on the object"},
        {"map.input.hint",          "Drag the middle to move  |  drag a corner to resize"},
        {"map.sidebar",             "Show / hide the properties panel"},
        {"slice.settings",          "SLICE SETTINGS"},
        {"sen.devices",             "DEVICES"},
        {"perf.title",              "PERFORMANCE"},
        {"cal.section",             "CALIBRATION & TRIGGER ZONES"},
        {"menu.project",            "Project"},
        {"menu.project.new",        "New"},
        {"menu.project.open",       "Open..."},
        {"menu.project.save",       "Save"},
        {"menu.output",             "Output"},
        {"menu.output.mapping",     "Mapping (edit in app)..."},
        {"menu.output.advanced",    "Advanced Output (values)..."},
        {"menu.output.sendto",      "Send output to display:"},
        {"menu.output.windowed",    "Back to windowed (to move it)"},
        {"menu.output.fullscreen",  "Fullscreen / exit"},
        {"menu.output.nodisplay",   "Cannot read display list"},
        {"menu.output.primary",     "  (primary)"},
        {"menu.sensor",             "Sensor"},
        {"menu.sensor.panel",       "Sensor & Calibration..."},
        {"menu.sensor.mock",        "Start Mock (simulated)"},
        {"menu.sensor.osc",         "Start OSC (port 9000)"},
        {"menu.sensor.stop",        "Stop sensor"},
        {"menu.sensor.autocal",     "Auto-calibrate (Mock)"},
        {"menu.sensor.crosshair",   "Show calibration crosshair"},
        {"menu.view",               "View"},
        {"menu.settings",           "Settings"},
        {"menu.settings.open",      "Settings..."},
        {"status.sensor.on",        "SENSOR: running"},
        {"status.sensor.off",       "SENSOR: off"},

        {"win.composition",         "Composition"},
        {"win.mapping",             "Mapping"},
        {"win.advanced",            "Advanced Output"},
        {"win.preview",             "Preview"},
        {"win.sensor",              "Sensor & Calibration"},
        {"win.perf",                "Performance"},
        {"win.clip",                "Clip"},
        {"win.settings",            "Settings"},

        {"set.language",            "Language"},
        {"set.language.note",       "Language change takes effect immediately."},
        {"set.output",              "Output"},
        {"set.output.default",      "Default display"},
        {"set.output.none",         "Do not send automatically"},
        {"set.vsync",               "Vertical sync"},
        {"set.media",               "Media"},
        {"set.media.budget",        "Media cache budget"},
        {"set.media.budget.note",   "High: smoother clip switching. Low: less VRAM."},
        {"set.media.warnhap",       "Warn when file is not HAP"},
        {"set.diag",                "Diagnostics"},
        {"set.perflog",             "Write performance log"},
        {"set.perflog.interval",    "Interval (seconds)"},
        {"set.perflog.note",        "Writes to bin/data/perf.log - use it to track down stutter."},
        {"set.startup",             "Startup"},
        {"set.autoplay",            "Auto-play first clip"},
        {"set.save",                "Save settings"},
        {"set.reset",               "Reset to defaults"},
        {"set.saved",               "Settings saved"},
        {"set.missing",             "Keys missing translation"},

        {"comp.deck",               "Deck:"},
        {"comp.clearall",           "Clear all"},
        {"comp.hint",               "Click clip = play  |  Click column number = play column  |  Ctrl+click = pick file"},
        {"layer.opacity",           "OPACITY"},
        {"comp.master",             "Master"},
        {"comp.empty",              "Empty grid"},
        {"comp.triggercol",         "Trigger column %d"},
        {"layer.solo.tip",          "Solo - hide all other layers"},
        {"layer.bypass.tip",        "Bypass - disable layer"},
        {"layer.clear.tip",         "Stop layer"},
        {"layer.transition.tip",    "A10 - clip transition length (crossfade). 0 = hard cut."},

        {"map.showcontent",         "Show content"},
        {"map.hint",                "Drag points to adjust  |  click a slice to select"},
        {"map.selecthint",          "Click a slice to select it"},
        {"map.outside",             "%d point(s) OUTSIDE the projector frame"},
        {"map.noscreen",            "No screen yet"},

        {"adv.overlay",             "Show edit overlay"},
        {"adv.grid",                "Test grid"},
        {"adv.addscreen",           "Add Screen"},
        {"adv.addslice",            "+ Add slice"},
        {"adv.slicelist",           "Slices (topmost last):"},
        {"adv.selected",            "Selected slice: %s"},
        {"adv.noslice",             "Select a slice to edit details"},
        {"adv.inputorigin",         "INPUT ORIGIN"},
        {"adv.inputsize",           "INPUT SIZE"},
        {"adv.source",              "TAKE CONTENT FROM"},
        {"adv.source.tip",          "Composition: the mixed image of all layers - use when several projectors form ONE surface.  |  Layer: a single layer, unmixed - use when surfaces run INDEPENDENT content."},
        {"adv.src.comp",            "Composition (mixed)"},
        {"adv.src.layer",           "A single Layer"},
        {"adv.src.which",           "LAYER NUMBER"},
        {"adv.src.missing",         "That layer no longer exists - the slice falls back to Composition. Pick another layer."},
        {"adv.warptype",            "WARP TYPE"},
        {"adv.warptype.tip",        "Corner pin: FLAT, 4 corners.  |  Mesh: N×M grid, each cell flat.  |  Bezier: smooth CURVED surface, 16 points — for columns, vaults, statues. Switching keeps the four corners you aligned."},
        {"adv.reset",               "Reset"},
        {"adv.delete",              "Delete"},
        {"adv.corners",             "CORNERS (NUMERIC)"},
        {"adv.broken",              "  ! Degenerate warp - unusable for sensor"},
        {"adv.color",               "Color (F19)"},
        {"adv.softedge",            "Soft edge (F20)"},
        {"adv.meshgrid",            "MESH (COLS X ROWS)"},
        {"adv.overlay.tip",         "Turn OFF during the show - the audience must not see handles"},
        {"adv.solo",                "solo"},
        {"adv.color.note",          "Needed when blending projectors: each one has its own tint."},
        {"adv.color.brightness",    "BRIGHTNESS"},
        {"adv.color.contrast",      "CONTRAST"},
        {"adv.color.gamma",         "GAMMA"},
        {"adv.color.rgb",           "RGB BALANCE"},
        {"adv.color.opacity",       "Slice opacity"},
        {"adv.color.reset",         "Reset color"},
        {"adv.color.default",       "(default)"},
        {"adv.color.edited",        "(edited)"},
        {"adv.edge.note1",          "Blending 2 projectors: overlap them 10-20%%,"},
        {"adv.edge.note2",          "each fades out towards the shared edge."},
        {"adv.edge.left",           "LEFT"},
        {"adv.edge.right",          "RIGHT"},
        {"adv.edge.top",            "TOP"},
        {"adv.edge.bottom",         "BOTTOM"},
        {"adv.edge.gamma",          "CURVE"},
        {"adv.edge.gamma.tip",      "1.0 = linear. Real projectors usually need 1.8-2.4 because their gamma response is non-linear."},
        {"adv.edge.mid",            "MIDPOINT"},
        {"adv.edge.reset",          "Reset edge"},
        {"adv.edge.off",            "(off)"},
        {"adv.edge.on",             "(on)"},
        {"adv.corner.tl",           "TOP-LEFT"},
        {"adv.corner.tr",           "TOP-RIGHT"},
        {"adv.corner.br",           "BOTTOM-RIGHT"},
        {"adv.corner.bl",           "BOTTOM-LEFT"},
        {"adv.corner.rejected",     "Corner position rejected: the quad would be concave or self-intersecting"},
        {"adv.mesh.hint",           "Drag mesh points in the Mapping window"},
        {"mask.title",              "Bezier mask (F12)"},
        {"mask.note",               "Trims the light to the real object silhouette."},
        {"mask.enabled",            "Enable mask"},
        {"mask.edit",               "Edit mask"},
        {"mask.edit.tip",           "While on, dragging in the Mapping window moves mask nodes instead of keystone corners."},
        {"mask.invert",             "Invert (cut a hole)"},
        {"mask.feather",            "FEATHER"},
        {"mask.feather.tip",        "A hard edge exposes every alignment error against the real object edge. A few percent is enough to hide it."},
        {"mask.shape.rect",         "Rectangle"},
        {"mask.shape.ellipse",      "Ellipse"},
        {"mask.clear",              "Clear mask"},
        {"mask.nodes",              "%d nodes"},
        {"mask.empty",              "No shape yet. Pick a preset to start."},
        {"mask.tooFew",             "A mask needs at least 3 nodes to have any effect."},
        {"mask.hint",               "Drag nodes to align  |  click the path = add node  |  right-click a node = delete"},
        {"mask.hint.handle",        "Ctrl+drag a node = curve it  |  Shift+click a node = straighten"},
        {"mask.cannotRemove",       "Cannot remove: a mask needs at least 3 nodes"},
        {"mask.full",               "Maximum node count reached"},

        {"clip.nosel",              "Click a clip's eye icon to see its properties"},
        {"clip.empty",              "This cell is empty"},
        {"clip.name",               "Name"},
        {"clip.transport",          "Transport"},
        {"clip.play",               "Play"},
        {"clip.pause",              "Pause"},
        {"clip.stop",               "Stop"},
        {"clip.playhead",           "Playhead"},
        {"clip.direction",          "Direction"},
        {"clip.speed",              "Speed"},
        {"clip.inout",              "In / Out"},
        {"clip.endaction",          "On clip end"},
        {"clip.trigger",            "Trigger style"},
        {"clip.transform",          "Transform"},
        {"clip.position",           "Position"},
        {"clip.scale",              "Scale"},
        {"clip.rotation",           "Rotation"},
        {"clip.fliph",              "Flip H"},
        {"clip.flipv",              "Flip V"},
        {"clip.resetxform",         "Reset transform"},
        {"clip.blending",           "Blending"},
        {"clip.opacity",            "Opacity"},
        {"clip.blend",              "BLEND"},
        {"clip.where",              "Layer %d  /  Column %d"},
        {"clip.mediainfo",          "%.0f x %.0f  |  %.2f s"},
        {"clip.dir.fwd",            "Forward"},
        {"clip.dir.rev",            "Reverse"},
        {"clip.dir.pp",             "Ping-pong"},
        {"clip.end.loop",           "Loop"},
        {"clip.end.stop",           "Stop"},
        {"clip.end.hold",           "Hold last frame"},
        {"clip.end.next",           "Next clip"},
        {"clip.end.rand",           "Random"},
        {"clip.trig.toggle",        "Toggle"},
        {"clip.trig.piano",         "Piano (hold)"},

        {"sen.source",              "SOURCE"},
        {"sen.run",                 "Start"},
        {"sen.stop",                "Stop"},
        {"sen.running",             "running"},
        {"sen.stopped",             "stopped"},
        {"sen.points",              "Touch points: %d   (with stable ID: %d)"},
        {"sen.filter",              "Noise filter (key F): %s"},
        {"cal.title",               "Calibration: %s"},
        {"cal.step",                "Step %d/4: touch the crosshair on the REAL OBJECT"},
        {"cal.target",              "Target point: (%.2f, %.2f) of the slice"},
        {"cal.crosshair",           "Show crosshair on projector (key C)"},
        {"cal.auto",                "Auto-calibrate (Mock)"},
        {"cal.add",                 "Record this point"},
        {"cal.skip",                "Skip"},
        {"cal.solve",               "Solve"},
        {"cal.clear",               "Clear all"},
        {"cal.recorded",            "Recorded: %d point(s) (%d enabled)"},
        {"cal.error",               "Error: %.2f px (max %.2f) - %s"},
        {"cal.good",                "GOOD"},
        {"cal.bad",                 "SHOULD RECALIBRATE"},
        {"cal.notyet",              "Not calibrated"},
        {"cal.points",              "Recorded points"},
        {"cal.none",                "No calibration profile"},
        {"sen.type.mock",           "Mock (simulated)"},
        {"sen.type.osc",            "OSC / UDP"},
        {"sen.type.tuio",           "TUIO (port 3333)"},
        {"common.on.caps",          "ON"},
        {"common.off.caps",         "OFF"},
        {"cal.auto.tip",            "Derives H_s from the known range of MockSource. Lets you test the whole chain with no hardware."},
        {"cal.inlier",              "Inliers: %d / %d"},
        {"cal.pair",                "#%d  sensor(%.0f, %.0f) -> out(%.0f, %.0f)%s"},
        {"cal.outlier",             "   [OUTLIER]"},

        {"zone.title",              "Trigger zones (G17)   -   fired: %d"},
        {"zone.last",               "Last: %s"},
        {"zone.add",                "+ Add zone"},
        {"zone.none",               "No zones yet. Touching the object will do nothing."},
        {"zone.enabled",            "Enabled"},
        {"zone.delete",             "Delete zone"},
        {"zone.position",           "Position"},
        {"zone.size",               "Size"},
        {"zone.action",             "Action"},
        {"zone.layer",              "Layer"},
        {"zone.column",             "Column"},
        {"zone.cooldown",           "Cooldown"},
        {"zone.touching",           "   [TOUCHING]"},
        {"zone.add.tip",            "Zones are defined in CANVAS space. Re-doing the keystone does not move them."},
        {"zone.name",               "Name"},
        {"zone.act.none",           "None"},
        {"zone.act.clip",           "Play clip"},
        {"zone.act.column",         "Play whole column"},
        {"zone.act.clearlayer",     "Clear layer"},
        {"zone.act.clearall",       "Clear all"},
        {"zone.cooldown.tip",       "MANDATORY with a real sensor. One touch produces dozens of Down events; without debouncing the clip re-triggers 30 times a second."},

        {"perf.frame",              "Frame: avg %.2f ms  p99 %.2f ms"},
        {"perf.latency",            "Sensor latency:"},
        {"perf.latency.note",       "(excluding projector input lag:"},
        {"perf.latency.note2",      " 16-80ms - enable Low Latency Mode)"},
        {"perf.nosensor",           "Sensor not running"},
        {"perf.dropped",            "Sensor frames dropped: %llu"},
        {"perf.overflow",           "Ring overflow: 0"},
        {"perf.overflow.bad",       "! Ring overflow: %llu - EVENTS LOST"},
        {"perf.malformed",          "Malformed OSC packets: %llu"},
        {"perf.drawn",              "Layers drawn: %d   Slices drawn: %d"},
        {"perf.media",              "Media loaded: %d   Evicted: %d"},
        {"perf.vram",               "VRAM (estimated): %s"},

        {"common.on",               "ON"},
        {"common.off",              "OFF"},
        {"preview.nocontent",       "No content yet"},
    };
    return t;
}

} // namespace

void setLanguage(Language l) {
    if (g_lang == l) return;
    g_lang = l;
    missingKeys().clear();   // đếm lại cho ngôn ngữ mới
}

Language language() { return g_lang; }

const char* t(const char* key) {
    if (key == nullptr) return "";

    const Table& tbl = (g_lang == Language::English) ? tableEN() : tableVI();
    const auto it = tbl.find(key);
    if (it != tbl.end()) return it->second;

    // Thiếu bản dịch → trả về chính KHOÁ. Thấy "slice.softedge.gamma"
    // trên màn hình thì biết ngay thiếu chuỗi nào và ở đâu.
    missingKeys().insert(key);
    return key;
}

int missingCount() { return static_cast<int>(missingKeys().size()); }

std::vector<std::pair<std::string, std::string>> dumpTable(Language l) {
    const Table& tb = (l == Language::English) ? tableEN() : tableVI();
    std::vector<std::pair<std::string, std::string>> out;
    out.reserve(tb.size());
    for (const auto& kv : tb) out.emplace_back(kv.first, kv.second);
    return out;
}

} // namespace i18n
} // namespace hexmap
