import { Language } from '../types';

export const translations = {
  en: {
    appTitle: 'MIKMAP',
    tagline: 'Projection Mapping & Sensor Engine',
    tabComposition: 'COMPOSITION',
    tabMapping: 'ADVANCED MAPPING',
    tabSensor: 'SENSOR I/O',
    
    // Header & Status
    fps: 'FPS',
    frameTime: 'Frame',
    latency: 'Latency',
    outputDisplay: 'OUTPUT 1: 1920x1080',
    showMode: 'Show Mode',
    testGrid: 'Test Grid',
    autoCalib: 'Auto Calib',
    fullscreen: 'Fullscreen',
    saveProject: 'Save Project',
    loadProject: 'Load Project',
    resetDemo: 'Reset Demo',
    settings: 'Settings',
    language: 'Language',
    
    // Composition view
    filesAndFx: 'FILES & EFFECTS',
    generators: 'Generators',
    vjLoops: 'VJ Loops',
    audioReact: 'Audio Reactive',
    masks: 'Masks',
    videoFx: 'Video Effects',
    preview: 'PREVIEW',
    liveOutput: 'LIVE OUTPUT',
    selectClipPrompt: 'SELECT CLIP',
    clipProps: 'CLIP',
    layerProps: 'LAYER',
    transform: 'Transform',
    scale: 'Scale',
    posX: 'Position X',
    posY: 'Position Y',
    rotation: 'Rotation',
    opacity: 'Opacity',
    blend: 'BLEND',
    speed: 'Speed',
    loopMode: 'Loop Mode',
    layerOp: 'OP',
    col: 'COL',
    solo: 'S',
    blind: 'B',
    bypass: 'V',

    // Mapping view
    mappingTree: 'MAPPING TREE',
    inputSelection: 'INPUT SELECTION',
    outputRouting: 'OUTPUT ROUTING',
    screenProps: 'Screen Properties',
    sliceProps: 'Slice Properties',
    maskProps: 'Mask Properties',
    outputDevice: 'OUTPUT DEVICE',
    resolution: 'Resolution',
    edgeBlending: 'EDGE BLENDING',
    bezierWarping: 'BEZIER / MESH WARPING',
    cornerPinWarping: '4-POINT KEYSTONE WARPING',
    maskShape: 'MASK SHAPE',
    invertMask: 'Invert Mask (Cut Hole)',
    feather: 'Feather',
    addScreen: 'Add Screen',
    addSlice: 'Add Slice',
    addMask: 'Add Mask',
    
    // Sensor I/O view
    deviceManager: 'DEVICE MANAGER',
    connect: 'CONNECT',
    connected: 'CONNECTED',
    disconnect: 'DISCONNECT',
    receiving: 'RECEIVING',
    radarView: '2D LiDAR / SENSOR RADAR',
    roiZone: 'ROI ZONE 1',
    editRoi: 'EDIT ROI',
    finishRoi: 'FINISH ROI',
    simulatedTouch: 'Click radar canvas to simulate touch',
    blobTracking: 'BLOB TRACKING & FILTER',
    noiseThreshold: 'Noise Threshold (One-Euro)',
    minBlobSize: 'Min Blob Size',
    parameterRouting: 'PARAMETER ROUTING',
    dataSources: 'DATA SOURCES',
    targets: 'TARGETS',
    autoMapBlob: 'AUTO-MAP CLOSEST BLOB',
    calibrationWizard: 'CALIBRATION WIZARD (DLT 4-POINT)',
    startWizard: 'Start Calibration',
    calibCrosshair: 'Touch crosshair on projector output',
    reprojectionError: 'RMS Reprojection Error',
    matrixHs: 'Computed Homography H_s'
  },
  vi: {
    appTitle: 'MIKMAP',
    tagline: 'Engine Projection Mapping & Sensor',
    tabComposition: 'BẢN DỰNG (COMPOSITION)',
    tabMapping: 'ÁNH XẠ CHI TIẾT (MAPPING)',
    tabSensor: 'KẾT NỐI SENSOR (I/O)',
    
    // Header & Status
    fps: 'FPS',
    frameTime: 'Khung hình',
    latency: 'Độ trễ',
    outputDisplay: 'ĐẦU RA 1: 1920x1080',
    showMode: 'Chế độ diễn (Show)',
    testGrid: 'Lưới kiểm tra (G)',
    autoCalib: 'Auto Calib (A)',
    fullscreen: 'Toàn màn hình (F11)',
    saveProject: 'Lưu dự án',
    loadProject: 'Mở dự án',
    resetDemo: 'Nạp mẫu mặc định',
    settings: 'Cài đặt',
    language: 'Ngôn ngữ',
    
    // Composition view
    filesAndFx: 'TỆP & HIỆU ỨNG',
    generators: 'Trình tạo hình',
    vjLoops: 'Vòng lặp VJ',
    audioReact: 'Phản ứng âm thanh',
    masks: 'Mặt nạ cắt',
    videoFx: 'Hiệu ứng Video',
    preview: 'XEM TRƯỚC (PREVIEW)',
    liveOutput: 'TRỰC TIẾP (LIVE OUTPUT)',
    selectClipPrompt: 'CHỌN Ô CLIP',
    clipProps: 'CLIP',
    layerProps: 'LỚP',
    transform: 'Biến đổi hình',
    scale: 'Tỉ lệ',
    posX: 'Vị trí X',
    posY: 'Vị trí Y',
    rotation: 'Góc xoay',
    opacity: 'Độ mờ đục',
    blend: 'HOÀ TRỘN',
    speed: 'Tốc độ',
    loopMode: 'Kiểu lặp',
    layerOp: 'MỜ',
    col: 'CỘT',
    solo: 'S',
    blind: 'B',
    bypass: 'V',

    // Mapping view
    mappingTree: 'CÂY ÁNH XẠ (TREE)',
    inputSelection: 'VÙNG LẤY NỘI DUNG',
    outputRouting: 'ĐƯỜNG RA MÁY CHIẾU',
    screenProps: 'Thiết lập Màn hình',
    sliceProps: 'Thiết lập Slice',
    maskProps: 'Thiết lập Mặt nạ',
    outputDevice: 'THIẾT BỊ ĐẦU RA',
    resolution: 'Độ phân giải',
    edgeBlending: 'HOÀ BIÊN (EDGE BLENDING)',
    bezierWarping: 'UỐN LƯỚI BEZIER / MESH',
    cornerPinWarping: 'KÉO 4 GÓC KEYSTONE',
    maskShape: 'HÌNH MẶT NẠ',
    invertMask: 'Đảo ngược mặt nạ (khoét lỗ)',
    feather: 'Độ mờ biên',
    addScreen: 'Thêm Màn hình',
    addSlice: 'Thêm Slice',
    addMask: 'Thêm Mặt nạ',
    
    // Sensor I/O view
    deviceManager: 'QUẢN LÝ THIẾT BỊ',
    connect: 'KẾT NỐI',
    connected: 'ĐÃ KẾT NỐI',
    disconnect: 'NGẮT KẾT NỐI',
    receiving: 'ĐANG NHẬN',
    radarView: 'RADAR 2D LiDAR & SENSOR',
    roiZone: 'VÙNG CẢM ỨNG 1',
    editRoi: 'CHỈNH VÙNG ROI',
    finishRoi: 'XONG VÙNG ROI',
    simulatedTouch: 'Nhấp lên radar để tạo điểm chạm thử',
    blobTracking: 'THEO DÕI ĐIỂM CHẠM & LỌC NHIỄU',
    noiseThreshold: 'Ngưỡng lọc nhiễu (One-Euro)',
    minBlobSize: 'Kích thước điểm tối thiểu',
    parameterRouting: 'ĐIỀU HƯỚNG TÍN HIỆU (PATCH BAY)',
    dataSources: 'NGUỒN DỮ LIỆU',
    targets: 'ĐÍCH TÁC ĐỘNG',
    autoMapBlob: 'TỰ GÁN ĐIỂM CHẠM GẦN NHẤT',
    calibrationWizard: 'HƯỚNG DẪN HIỆU CHUẨN (DLT 4 ĐIỂM)',
    startWizard: 'Bắt đầu Calibrate',
    calibCrosshair: 'Chạm vào tâm dấu thập trên máy chiếu',
    reprojectionError: 'Sai số tái chiếu RMS',
    matrixHs: 'Ma trận Homography H_s tính được'
  }
};
